using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public  partial class ModelSync
{
    [RealtimeProperty(1, true, true)]
    private string _shirts;
}   

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ModelSync : RealtimeModel {
    public string shirts {
        get {
            return _shirtsProperty.value;
        }
        set {
            if (_shirtsProperty.value == value) return;
            _shirtsProperty.value = value;
            InvalidateReliableLength();
            FireShirtsDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ModelSync model, T value);
    public event PropertyChangedHandler<string> shirtsDidChange;
    
    public enum PropertyID : uint {
        Shirts = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _shirtsProperty;
    
    #endregion
    
    public ModelSync() : base(null) {
        _shirtsProperty = new ReliableProperty<string>(1, _shirts);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _shirtsProperty.UnsubscribeCallback();
    }
    
    private void FireShirtsDidChange(string value) {
        try {
            shirtsDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _shirtsProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _shirtsProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Shirts: {
                    changed = _shirtsProperty.Read(stream, context);
                    if (changed) FireShirtsDidChange(shirts);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _shirts = shirts;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
